
#define PANDA_MAJOR_VERSION 1
#define PANDA_MINOR_VERSION 10
#define PANDA_SEQUENCE_VERSION 0
#define PANDA_VERSION 1009999
#define PANDA_NUMERIC_VERSION 1009999
#define PANDA_VERSION_STR "1.10.0"
#define PANDA_ABI_VERSION_STR "1.10"
#define PANDA_DISTRIBUTOR "makepanda"
#define PANDA_PACKAGE_VERSION_STR "dev"
#define PANDA_PACKAGE_HOST_URL ""

#undef  PANDA_OFFICIAL_VERSION
